server:
  port: 8013
# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn
  # log config
  config: classpath:logback.xml
spring:
  application:
    name: ruoyi-socket
   # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  
feign: 
  hystrix: 
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eureka7001.com:7001/eureka
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址

socket:
  tcp-port: 29998
  boss-count: 1
  worker-count: 10
  keep-alive: true
  backlog: 100